namespace PixelPushers.MonoZelda.Tiles;

internal enum TileType
{
    //TODO: Testing with player sprites
    fire,
    bomb,
    cloud,
    arrow_blue_right,
    Statue,
    SquareBlock,
    PushableBlock,
    BlueGap,
    Stairs,
    WhiteBrick,
    Ladder,
    BlueFloor,    
    BlueSand,
    NorthDoorway,
    EastDoorway,
    SouthDoorway,
    WestDoorway,
    NorthKeyDoor,
    EastKeyDoor,
    SouthKeyDoor,
    WestKeyDoor,
    NorthDiamondDoor,
    EastDiamondDoor,
    SouthDiamondDoor,
    WestDiamondDoor,
    NorthBombableDoor,
    EastBombableDoor,
    SouthBombableDoor,
    WestBombableDoor,
    NorthBombedDoor,
    EastBombedDoor,
    SouthBombedDoor,
    WestBombedDoor,
}